#!/bin/python3

import math
import os
import random
import re
import sys

class SinglyLinkedListNode:
    def __init__(self, node_data):
        self.data = node_data
        self.next = None

class SinglyLinkedList:
    def __init__(self):
        self.head = None
        self.tail = None

    def insert_node(self, node_data):
        node = SinglyLinkedListNode(node_data)

        if not self.head:
            self.head = node
        else:
            self.tail.next = node


        self.tail = node

def print_singly_linked_list(node, sep):
    while node:
        print(node.data, end='')

        node = node.next

        if node:
            print(sep, end='')

#
# Complete the 'reversePrint' function below.
#
# The function accepts INTEGER_SINGLY_LINKED_LIST llist as parameter.
#

#
# For your reference:
#
# SinglyLinkedListNode:
#     int data
#     SinglyLinkedListNode next
# list      3 2 1
# previous   2
# last  1


def getLastNode(list):

    if(list.next is None):
        return list.data 
    
    previous = list
    last = previous.next

    while last.next is not None:
        previous = previous.next
        last = previous.next

    previous.next = None

    return last.data

def reversePrint(llist):
    # Write your code here

    if (llist is None or llist.head is None):
        return llist
    
    copy = llist.head
    reversed = SinglyLinkedList()

    while copy.next is not None:
        reversed.insert_node(getLastNode(copy))
    
    reversed.insert_node(copy.data)

    print_singly_linked_list(reversed.head, "\n")
    

if __name__ == '__main__':
    reversed = SinglyLinkedList()
    reversed.insert_node(10)
    reversed.insert_node(9)
    reversed.insert_node(8)
    reversed.insert_node(7)
    reversed.insert_node(6)
    reversePrint(reversed)
